// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3IytQezozufw9rajz_0tD1yAGBfQpqqo',
    appId: '1:664133474691:web:c1ca5db396376036bbfeb6',
    messagingSenderId: '664133474691',
    projectId: 'lddm-2023',
    authDomain: 'lddm-2023.firebaseapp.com',
    storageBucket: 'lddm-2023.appspot.com',
    measurementId: 'G-0QJHP6781F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBu_4qQDK1EydKoyHJmsyukiqYUsM9nYbM',
    appId: '1:664133474691:android:59e5634192f73170bbfeb6',
    messagingSenderId: '664133474691',
    projectId: 'lddm-2023',
    storageBucket: 'lddm-2023.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNjUqezgD_MXIbL-5X4XsaaS8pImD1aoQ',
    appId: '1:664133474691:ios:f6ebf1b4e3549df3bbfeb6',
    messagingSenderId: '664133474691',
    projectId: 'lddm-2023',
    storageBucket: 'lddm-2023.appspot.com',
    iosBundleId: 'com.example.pricely',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNjUqezgD_MXIbL-5X4XsaaS8pImD1aoQ',
    appId: '1:664133474691:ios:e40e37ecd9b0e834bbfeb6',
    messagingSenderId: '664133474691',
    projectId: 'lddm-2023',
    storageBucket: 'lddm-2023.appspot.com',
    iosBundleId: 'com.example.pricely.RunnerTests',
  );
}
